# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170514_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(default='Default About')),
            ],
        ),
    ]
