# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:45
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
