# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20170607_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='info',
            field=redactor.fields.RedactorField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(max_length=300),
        ),
    ]
